apiVersion: v1
data:
  config.yaml: |-
    terraformOutput: {{ .Values.terraformOutput }}
kind: ConfigMap
metadata:
  name: {{ include "terraform-output.fullname" . }}-runtime-configmap
  namespace: {{ .Release.Namespace }}