ce51ddfss3mdcc:
  folder_title: production
  folder_uid: ee51dc4vn9gqoe
  json: '{"annotations": {"list": [{"builtIn": 1, "datasource": {"type": "grafana",
    "uid": "-- Grafana --"}, "enable": true, "hide": true, "iconColor": "rgba(0, 211,
    255, 1)", "name": "Annotations & Alerts", "type": "dashboard"}]}, "editable":
    true, "fiscalYearStartMonth": 0, "graphTooltip": 0, "id": 471, "links": [], "panels":
    [{"datasource": {"type": "grafana", "uid": "grafana"}, "fieldConfig": {"defaults":
    {"color": {"mode": "palette-classic"}, "custom": {"axisBorderShow": false, "axisCenteredZero":
    false, "axisColorMode": "text", "axisLabel": "", "axisPlacement": "auto", "fillOpacity":
    80, "gradientMode": "none", "hideFrom": {"legend": false, "tooltip": false, "viz":
    false}, "lineWidth": 1, "scaleDistribution": {"type": "linear"}, "thresholdsStyle":
    {"mode": "off"}}, "mappings": [], "thresholds": {"mode": "absolute", "steps":
    [{"color": "green", "value": null}, {"color": "red", "value": 80}]}}, "overrides":
    []}, "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}, "id": 1, "options": {"barRadius":
    0, "barWidth": 0.97, "fullHighlight": false, "groupWidth": 0.7, "legend": {"calcs":
    [], "displayMode": "list", "placement": "bottom", "showLegend": true}, "orientation":
    "auto", "showValue": "auto", "stacking": "none", "tooltip": {"mode": "single",
    "sort": "none"}, "xTickLabelRotation": 0, "xTickLabelSpacing": 0}, "targets":
    [{"datasource": {"type": "datasource", "uid": "grafana"}, "queryType": "randomWalk",
    "refId": "A"}], "title": "Panel Title", "type": "barchart"}], "schemaVersion":
    39, "tags": ["v1.0.0"], "templating": {"list": []}, "time": {"from": "now-6h",
    "to": "now"}, "timepicker": {}, "timezone": "browser", "title": "walk", "uid":
    "ce51ddfss3mdcc", "version": 2, "weekStart": ""}'
  tags:
  - v1.0.0
  title: walk
fe40gkfjmzmrkf:
  folder_title: sync-folder
  folder_uid: de50nm7qz9f5sf
  json: '{"annotations": {"list": [{"builtIn": 1, "datasource": {"type": "grafana",
    "uid": "-- Grafana --"}, "enable": true, "hide": true, "iconColor": "rgba(0, 211,
    255, 1)", "name": "Annotations & Alerts", "type": "dashboard"}]}, "editable":
    true, "fiscalYearStartMonth": 0, "graphTooltip": 0, "id": 469, "links": [], "panels":
    [{"datasource": {"type": "datasource", "uid": "grafana"}, "fieldConfig": {"defaults":
    {"color": {"mode": "palette-classic"}, "custom": {"axisBorderShow": false, "axisCenteredZero":
    false, "axisColorMode": "text", "axisLabel": "", "axisPlacement": "auto", "barAlignment":
    0, "drawStyle": "line", "fillOpacity": 0, "gradientMode": "none", "hideFrom":
    {"legend": false, "tooltip": false, "viz": false}, "insertNulls": false, "lineInterpolation":
    "linear", "lineWidth": 1, "pointSize": 5, "scaleDistribution": {"type": "linear"},
    "showPoints": "auto", "spanNulls": false, "stacking": {"group": "A", "mode": "none"},
    "thresholdsStyle": {"mode": "off"}}, "mappings": [], "thresholds": {"mode": "absolute",
    "steps": [{"color": "green", "value": null}, {"color": "red", "value": 80}]}},
    "overrides": []}, "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}, "id": 1, "options":
    {"legend": {"calcs": [], "displayMode": "list", "placement": "bottom", "showLegend":
    true}, "tooltip": {"mode": "single", "sort": "none"}}, "title": "Panel Title",
    "type": "timeseries"}], "schemaVersion": 39, "tags": [], "templating": {"list":
    []}, "time": {"from": "now-6h", "to": "now"}, "timepicker": {}, "timezone": "browser",
    "title": "dashboard-2", "uid": "fe40gkfjmzmrkf", "version": 2, "weekStart": ""}'
  tags: v0.0.1
  title: dashboard-2
fe50gkfjmzmrkf:
  folder_title: sync-folder
  folder_uid: de50nm7qz9f5sf
  json: '{"annotations": {"list": [{"builtIn": 1, "datasource": {"type": "grafana",
    "uid": "-- Grafana --"}, "enable": true, "hide": true, "iconColor": "rgba(0, 211,
    255, 1)", "name": "Annotations & Alerts", "type": "dashboard"}]}, "editable":
    true, "fiscalYearStartMonth": 0, "graphTooltip": 0, "id": 468, "links": [], "panels":
    [{"datasource": {"type": "datasource", "uid": "grafana"}, "fieldConfig": {"defaults":
    {"color": {"mode": "palette-classic"}, "custom": {"axisBorderShow": false, "axisCenteredZero":
    false, "axisColorMode": "text", "axisLabel": "", "axisPlacement": "auto", "barAlignment":
    0, "drawStyle": "line", "fillOpacity": 0, "gradientMode": "none", "hideFrom":
    {"legend": false, "tooltip": false, "viz": false}, "insertNulls": false, "lineInterpolation":
    "linear", "lineWidth": 1, "pointSize": 5, "scaleDistribution": {"type": "linear"},
    "showPoints": "auto", "spanNulls": false, "stacking": {"group": "A", "mode": "none"},
    "thresholdsStyle": {"mode": "off"}}, "mappings": [], "thresholds": {"mode": "absolute",
    "steps": [{"color": "green", "value": null}, {"color": "red", "value": 80}]}},
    "overrides": []}, "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}, "id": 1, "options":
    {"legend": {"calcs": [], "displayMode": "list", "placement": "bottom", "showLegend":
    true}, "tooltip": {"mode": "single", "sort": "none"}}, "title": "Panel Title",
    "type": "timeseries"}], "schemaVersion": 39, "tags": [], "templating": {"list":
    []}, "time": {"from": "now-6h", "to": "now"}, "timepicker": {}, "timezone": "browser",
    "title": "dashboard-1", "uid": "fe50gkfjmzmrkf", "version": 2, "weekStart": ""}'
  tags: v0.0.1
  title: dashboard-1
