apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - application: alertmanager
        namespace: default
        targetRevision: HEAD
      - application: grafana-operator
        namespace: default
        targetRevision: HEAD
      - application: grafana-crd
        namespace: default
        targetRevision: HEAD
  template:
    metadata:
      name: 'kchestnov-{{.application}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kchestnov/argocd-examples-kchestnov
        targetRevision: '{{.targetRevision}}'
        path: 'helm-chart-{{.application}}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{.namespace}}'