apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/kchestnov/argocd-examples-kchestnov
      revision: main
      directories:
        - path: apps/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kchestnov/argocd-examples-kchestnov
        targetRevision: 'HEAD'
        path: '{{ path }}'
      helm:
        valueFiles:
          - values.yaml
          - "*-values.yaml"
          
      destination:
        server: "https://kubernetes.default.svc"
        namespace: 'default'