apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-dev
  labels:
    dashboards: "grafana-dev"
spec:
  config:
    log:
      mode: "console"
    security:
      admin_user: root
      admin_password: secret
